// pages/UpdatePlan.jsx
import { useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useStore } from '../stores/useStore';
import { RiskBadge, Spinner, EmptyState } from '../components/shared';
import { ArrowUpCircle, Replace, Trash2, Eye, Zap } from 'lucide-react';

const PRIORITY_ORDER = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };

const ACTION_ICON = {
  UPDATE:  { icon: ArrowUpCircle, color: 'text-blue-400' },
  REPLACE: { icon: Replace,       color: 'text-orange-400' },
  REMOVE:  { icon: Trash2,        color: 'text-red-400' },
  MONITOR: { icon: Eye,           color: 'text-gray-400' },
};

const EFFORT_COLOR = {
  '< 1h':    'text-green-400',
  '2-4h':    'text-yellow-400',
  '1 day':   'text-orange-400',
  '> 1 day': 'text-red-400',
};

const BREAKING_COLOR = {
  LOW:      'text-green-400',
  MODERATE: 'text-yellow-400',
  HIGH:     'text-red-400',
};

export default function UpdatePlan() {
  const { reportId } = useParams();
  const { activeReport, fetchReport, activeReportLoading } = useStore();

  useEffect(() => {
    if (reportId && !activeReport) fetchReport(reportId);
  }, [reportId]);

  if (activeReportLoading) return <div className="flex items-center justify-center h-full"><Spinner size={10} /></div>;
  if (!activeReport) return <EmptyState icon="🤖" title="No report loaded" description="Run an analysis first." />;

  const plan = activeReport.update_plan || {};
  const updates = [...(plan.updates || [])].sort(
    (a, b) => (PRIORITY_ORDER[a.priority] ?? 99) - (PRIORITY_ORDER[b.priority] ?? 99)
  );

  const isFallback = plan._fallback;

  return (
    <div className="p-6 space-y-6 overflow-y-auto h-full">
      {/* Header */}
      <div className="flex items-start gap-3">
        <div className="p-2 bg-blue-900/40 rounded-lg">
          <Zap size={20} className="text-blue-400" />
        </div>
        <div className="flex-1">
          <h1 className="text-xl font-bold text-white">AI-Powered Update Plan</h1>
          <p className="text-sm text-gray-400 mt-0.5">
            {isFallback
              ? 'Generated by deterministic rules (AI unavailable)'
              : 'Generated by Claude AI · Sorted by risk priority'}
          </p>
        </div>
        {plan.total_risk_reduction && (
          <div className="bg-green-900/30 border border-green-700 rounded-lg px-3 py-2 text-center">
            <p className="text-xs text-gray-400">Estimated risk reduction</p>
            <p className="text-lg font-bold text-green-400">{plan.total_risk_reduction}</p>
          </div>
        )}
      </div>

      {/* Executive summary */}
      {plan.executive_summary && (
        <div className="bg-blue-950/40 border border-blue-800/50 rounded-xl p-4">
          <p className="text-xs text-blue-400 font-semibold uppercase tracking-wide mb-2">Executive Summary</p>
          <p className="text-sm text-gray-200 leading-relaxed">{plan.executive_summary}</p>
        </div>
      )}

      {/* Stats row */}
      <div className="flex gap-4 flex-wrap">
        {['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map(level => {
          const count = updates.filter(u => u.priority === level).length;
          if (!count) return null;
          const colors = {
            CRITICAL: 'border-red-700 text-red-400',
            HIGH:     'border-orange-600 text-orange-400',
            MEDIUM:   'border-yellow-600 text-yellow-400',
            LOW:      'border-gray-600 text-gray-400',
          };
          return (
            <div key={level} className={`bg-gray-800 border rounded-lg px-4 py-2 ${colors[level]}`}>
              <span className="text-lg font-bold">{count}</span>
              <span className="text-xs ml-2">{level}</span>
            </div>
          );
        })}
      </div>

      {/* Update cards */}
      {updates.length === 0 ? (
        <EmptyState icon="✅" title="No updates required" description="All dependencies are up to date and low risk." />
      ) : (
        <div className="space-y-3">
          {updates.map((update, i) => {
            const ActionIconConfig = ACTION_ICON[update.action] || ACTION_ICON.UPDATE;
            const ActionIcon = ActionIconConfig.icon;

            return (
              <div key={update.purl || i} className="bg-gray-800 border border-gray-700 rounded-xl p-4 hover:border-gray-600 transition">
                <div className="flex items-start gap-3">
                  <ActionIcon size={18} className={`${ActionIconConfig.color} flex-shrink-0 mt-0.5`} />
                  <div className="flex-1 min-w-0">
                    {/* Top row */}
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-semibold text-white">{update.name}</span>
                      <span className="font-mono text-xs text-gray-400">
                        {update.current_version} → <span className="text-green-400">{update.recommended_version}</span>
                      </span>
                      <RiskBadge level={update.priority} />
                      <span className={`text-xs font-medium ${ActionIconConfig.color}`}>{update.action}</span>
                    </div>

                    {/* Main reason */}
                    <p className="text-sm text-gray-300 mt-2">{update.main_reason}</p>

                    {/* Replacement suggestion */}
                    {update.replacement_suggestion && (
                      <p className="text-xs text-blue-300 mt-1">
                        💡 Suggested replacement: <span className="font-medium">{update.replacement_suggestion}</span>
                      </p>
                    )}

                    {/* Notes */}
                    {update.notes && (
                      <div className="mt-2 bg-gray-900/60 rounded p-2">
                        <p className="text-xs text-gray-400 leading-relaxed">{update.notes}</p>
                      </div>
                    )}

                    {/* Meta row */}
                    <div className="flex gap-4 mt-3 flex-wrap">
                      <div>
                        <span className="text-xs text-gray-500">Breaking risk: </span>
                        <span className={`text-xs font-semibold ${BREAKING_COLOR[update.breaking_risk] || 'text-gray-300'}`}>
                          {update.breaking_risk}
                        </span>
                      </div>
                      <div>
                        <span className="text-xs text-gray-500">Effort: </span>
                        <span className={`text-xs font-semibold ${EFFORT_COLOR[update.migration_effort] || 'text-gray-300'}`}>
                          {update.migration_effort}
                        </span>
                      </div>
                      <div className="text-xs text-gray-600 truncate max-w-xs font-mono">{update.purl}</div>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
